#!/bin/bash

# modify lines 11-14 with values to suit your environment regarding
# users and groups. This keeps the output files' permissions as expected.
# my username and group on my setup is 'ubuntu' and the ids are 1000, 1000
docker run --rm -it \
	-v $(pwd):$(pwd) \
	-w $(pwd) \
	-p 8000:8000 \
dmmmdfll/nikola/debian \
	-U ubuntu \
	-u 1000 \
	-G ubuntu \
	-g 1000 \
/nikola-virtualenv/bin/nikola "$@"
